---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-ca.name" . }}-secrets
  namespace: {{ include "metavac-ca.namespace" . }}
type: Opaque
data:
  ca.crt: {{ .Files.Get (cat .Values.cert_source_dir "/" "ca.crt" | nospace) | b64enc | quote }}
  ca.key: {{ .Files.Get (cat .Values.cert_source_dir "/" "ca.key" | nospace) | b64enc | quote }}