all:
  hosts:
    node1:
      ansible_host: dev.metavac.ac
      ip: dev.metavac.ac
      access_ip: dev.metavac.ac
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
