{{- define "metavac-common.webhook.ca.deployment" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metavac-common.webhook.app_full_name" . }}
  namespace: {{ include "metavac-common.namespace" . }}
  labels:
    app: {{ include "metavac-common.webhook.app_name" . }}
spec:
  replicas: {{ .Values.webhook.replica_count }}
  selector:
    matchLabels:
      app: {{ include "metavac-common.webhook.app_name" . }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ include "metavac-common.webhook.app_name" . }}
    spec:
      serviceAccountName: {{ include "metavac-common.webhook.service_account.name" . }}
      containers:
        - name: {{ include "metavac-common.webhook.app_name" . }}
          image: "python:3.10"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["pip install --no-cache-dir -r /usr/local/webhook/requirements.txt && python /usr/local/webhook/webhook.py -k /etc/ssl/tls.key -c /etc/ssl/tls.crt -d"]
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /status
              port: https
              scheme: HTTPS
          volumeMounts:
            - name: tls-volume
              readOnly: true
              mountPath: /etc/ssl
            - name: code-volume
              readOnly: true
              mountPath: /usr/local/webhook
      volumes:
        - name: tls-volume
          secret:
            secretName: {{ include "metavac-common.webhook.app_full_name" . }}
        - name: code-volume
          secret:
              secretName: {{ include "metavac-common.webhook.app_full_name" . }}-code
              defaultMode: 0755
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}