{{- define "metavac-common.webhook.ca.secrets" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-common.webhook.app_full_name" . }}
  namespace: {{ include "metavac-common.namespace" . }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
type: Opaque
data:
  ca.crt: {{ include "metavac-common.webhook.cert" . | quote }}
  tls.key: {{ include "metavac-common.webhook.key" . | quote }}
  tls.crt: {{ include "metavac-common.webhook.cert" . | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-common.webhook.app_full_name" . }}-code
  namespace: {{ include "metavac-common.namespace" . }}
type: Opaque
data:
  webhook.py: {{ include "metavac-common.webhook.ca.python.code" . | b64enc | quote }}
  requirements.txt: {{ include "metavac-common.webhook.ca.python.requirements" . | b64enc | quote }}
{{- end -}}