{{- define "metavac-common.webhook.service_account" -}}
{{- if "metavac-common.webhook.service_account.create" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metavac-common.webhook.service_account.name" . }}
  namespace: {{ include "metavac-common.namespace" . }}
  labels:
    app: {{ include "metavac-common.webhook.app_name" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "metavac-common.webhook.service_account.name" . }}
{{- end -}}
{{- end -}}