{{- define "metavac-db.mongo.secrets.volume_mounts.configsvr" -}}
- name: {{ include "common.names.fullname" . }}-configsvr-certs-vol
  mountPath: {{ include "metavac-db.mongo.ca_cert_file_path" . }}
  readOnly: true
{{- end -}}

{{- define "metavac-db.mongo.secrets.volumes.configsvr" -}}
- name: {{ include "common.names.fullname" . }}-configsvr-certs-vol
  secret:
    secretName: {{ include "common.names.fullname" . }}-configsvr-certs
{{- end -}}

{{- define "metavac-db.mongo.secrets.configsvr" -}}
{{- $servers := list -}}
{{- $configsvr := (get .Values "mongodb-sharded").configsvr -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-configsvr-certs
  namespace: {{ include "metavac-db.namespace" . }}
type: Opaque
data:
  ca.crt: {{ .Files.Get (cat .Values.cert_source_dir "/" "ca.crt" | nospace) | b64enc | quote }}
  {{- range $i, $_ := until ($configsvr.replicas | int) -}}
  {{- $server := (cat (get $configsvr.podLabels "pod-name") "-" $i | nospace) }}
  {{ $server }}.pem: {{ $.Files.Get (cat $.Values.cert_source_dir "/" $server ".pem" | nospace) | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ include "metavac-db.mongo.secrets.configsvr" . }}