{{- define "metavac-db.mongo.secrets.volume_mounts.configsvr" -}}
- name: {{ include "metavac-db.fullname" . }}-configsvr-certs-vol
  mountPath: {{ .Values.global.cert_mongo_dir }}
  readOnly: true
{{- end -}}

{{- define "metavac-db.mongo.secrets.volumes.configsvr" -}}
- name: {{ include "metavac-db.fullname" . }}-configsvr-certs-vol
  secret:
    secretName: {{ include "metavac-db.fullname" . }}-configsvr-certs
{{- end -}}

{{- define "metavac-db.mongo.secrets.configsvr" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-db.fullname" . }}-configsvr-certs
  namespace: {{ include "metavac-db.namespace" . }}
type: kubernetes.io/tls
data:
  ca.crt: |
    {{- printf "\n" }}{{- .Files.Get (cat .Values.cert_source_dir "/" "ca.crt" | nospace) | indent 4 }}
  id.pem: |
    {{- printf "\n" }}{{- .Files.Get (cat .Values.cert_source_dir "/" "configsvr.key" | nospace) | indent 4 }}
{{- end -}}

{{ include "metavac-db.mongo.secrets.configsvr" . }}