{{- define "metavac-db.mongo.secrets.volume_mounts.mongos" -}}
- name: {{ include "metavac-db.fullname" . }}-mongos-certs-vol
  mountPath: {{ include "metavac-db.mongo.ca_cert_file_path" . }}
  readOnly: true
{{- end -}}

{{- define "metavac-db.mongo.secrets.volumes.mongos" -}}
- name: {{ include "metavac-db.fullname" . }}-mongos-certs-vol
  secret:
    secretName: {{ include "metavac-db.fullname" . }}-mongos-certs
{{- end -}}

{{- define "metavac-db.mongo.secrets.mongos" -}}
{{- $servers := list -}}
{{- $mongos := (get .Values "mongodb-sharded").mongos -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-db.fullname" . }}-mongos-certs
  namespace: {{ include "metavac-db.namespace" . }}
type: Opaque
data:
  ca.crt: {{ .Files.Get (cat .Values.cert_source_dir "/" "ca.crt" | nospace) | b64enc | quote }}
  {{- range $i, $_ := until ($mongos.replicas | int) -}}
  {{- $server := (cat (get $mongos.podLabels "pod-name") "-" $i | nospace) }}
  {{ $server }}.pem: {{ $.Files.Get (cat $.Values.cert_source_dir "/" $server ".pem" | nospace) | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ include "metavac-db.mongo.secrets.mongos" . }}