{{- define "metavac-db.mongo.secrets.volume_mounts.shardsvr" -}}
- name: {{ include "metavac-db.fullname" . }}-shardsvr-certs-vol
  mountPath: {{ .Values.global.cert_mongo_dir }}
  readOnly: true
{{- end -}}

{{- define "metavac-db.mongo.secrets.volumes.shardsvr" -}}
- name: {{ include "metavac-db.fullname" . }}-shardsvr-certs-vol
  secret:
    secretName: {{ include "metavac-db.fullname" . }}-shardsvr-certs
{{- end -}}

{{- define "metavac-db.mongo.secrets.shardsvr" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metavac-db.fullname" . }}-shardsvr-certs
  namespace: {{ include "metavac-db.namespace" . }}
type: kubernetes.io/tls
data:
  ca.crt: |
    {{- printf "\n" }}{{- .Files.Get (cat .Values.cert_source_dir "/" "ca.crt" | nospace) | indent 4 }}
  id.pem: |
    {{- printf "\n" }}{{- .Files.Get (cat .Values.cert_source_dir "/" "shardsvr.key" | nospace) | indent 4 }}
{{- end -}}

{{ include "metavac-db.mongo.secrets.shardsvr" . }}