# Default values for metavac-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cert_source_dir: "certs"

global:
  name: "metavac-db"
  namespace: "dev"

  mongoMount: "/mnt/mongo"
  logDir: "{{ .Values.global.mongoMount }}/logs"

  cert_mongo_dir: "{{ .Values.global.mongoMount }}/ssl"

db:
  name: "metavac"
  url: "localhost:27017/metavac"
  ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIIDTzCCAjegAwIBAgIUJ6LOIde+ls/1aV41DWrdBYEpQLUwDQYJKoZIhvcNAQEL
    BQAwNzETMBEGA1UEAwwKbWV0YXZhYy5hYzEOMAwGA1UECwwFSW5mcmExEDAOBgNV
    BAoMB01ldGF2YWMwHhcNMjIwMjA2MDI1NzAzWhcNMjMwMjA2MDI1NzAzWjA3MRMw
    EQYDVQQDDAptZXRhdmFjLmFjMQ4wDAYDVQQLDAVJbmZyYTEQMA4GA1UECgwHTWV0
    YXZhYzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKA3dbujNPRAewSF
    x7tRqX7vuTOslo8Ogcck3OoSClz6YOYmglFK/tZnO5rKISsABbjUY2Gqv11ESB8i
    OUzmDde176u35vbFF+eeHSbfRbSP9++Xx7eNNFzNBHhoyEDVXY0bXix25LKqypPP
    YQlpztIz56UWvCIVgYvf/YC8Cwydlk2N0eszx8Sj64ISibBHoBGS7MIZHpp2g6cc
    PrThT62J9bqrqi5u77XgG8j2Mi4UKhmQlpCh3t8jhLLW/d/Bcj3ZHq5dFwQuWGz0
    Vqfp10jQc7UXhhDbYlgVDSBl57lQt+CK4vm7+O8N8O9Q9l6jpl+G25tfs0REXTNJ
    hLP3ZwkCAwEAAaNTMFEwHQYDVR0OBBYEFHpt3Dag9McrtLgNfTocnu4vKUhjMB8G
    A1UdIwQYMBaAFHpt3Dag9McrtLgNfTocnu4vKUhjMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAE6H5uM9hJQm5uRvdE/Ium30Z6AdLQuT9NDvPSgz
    7sRna+bk4CXBNhc8aGl03LnjQWGGJjc4nZqEn2mQ9aT69KvkVJWEfWwSxH256WGC
    DEeVxAIFr5oOYz+R2rSSAFiBpcT5i/zbdMv+DWp/Qx/hurjJ0wZQkYf+C+BqDsWS
    0aftgVMsD7G8nVrZBZxJDaHYG8YMABUydlWtCynV387KA0vgEB/AWIii170qaCdf
    mo+Pv5JAowsLYTw0Fv91jLx8yxthlhnmP/9C2OE8ozRTOAeTLM/jEkuV6loeMtIh
    XNqoHt3I9gmMG/TB5X8ftzfaSsLs4a5DFUV3yEXaKnRyw0U=
    -----END CERTIFICATE-----
  

mongodb-sharded:
  nameOverride: "metavac-db"
  shards: 2
  configsvr:
    replicas: 1
    config: "{{ include \"metavac-db.mongo.conf.configsvr\" . }}"
    podLabels:
      pod-name: metavac-db-configsvr
    persistence:
      mountPath: "/mnt/mongo"
      storageClass: "local-storage"
      size: "4Gi"
    extraVolumes:
      - "{{ include \"metavac-db.mongo.secrets.volumes.configsvr\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volumes.configsvr\" . }}"
    extraVolumeMounts:
      - "{{ include \"metavac-db.mongo.secrets.volume_mounts.configsvr\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volume_mounts.configsvr\" . }}"
  mongos:
    replicas: 2
    config: "{{ include \"metavac-db.mongo.conf.mongos\" . }}"
    podLabels:
      pod-name: metavac-db-mongos
    useStatefulSet: true
    servicePerReplica:
      nodePort: 30007
    extraVolumes:
      - "{{ include \"metavac-db.mongo.secrets.volumes.mongos\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volumes.mongos\" . }}"
    extraVolumeMounts:
      - "{{ include \"metavac-db.mongo.secrets.volume_mounts.mongos\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volume_mounts.mongos\" . }}"
  shardsvr:
    replicas: 1
    config: "{{ include \"metavac-db.mongo.conf.shardsvr\" . }}"
    podLabels:
      pod-name: metavac-db-shardsvr
    persistence:
      mountPath: "/mnt/mongo"
      size: "4Gi"
    extraVolumes:
      - "{{ include \"metavac-db.mongo.secrets.volumes.shardsvr\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volumes.shardsvr\" . }}"
    extraVolumeMounts:
      - "{{ include \"metavac-db.mongo.secrets.volume_mounts.shardsvr\" . }}"
      - "{{ include \"metavac-db.mongo.bootstrap.volume_mounts.shardsvr\" . }}"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}