# Default values for metavac-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

local_storage:
  enabled: true
  class_name: local-storage
  local_path: /mnt/local

cert_source_dir: "certs"

global:
  name: "metavac-db"
  namespace: "metavac-db"
  cluster_domain: "db.dev.metavac.ac"

  db_name: "metavac"
  url: "localhost:27017/metavac"

  mount: "/data"
  log_path: "{{ tpl .Values.global.mount . }}/logs/log"
  db_dir: "{{ tpl .Values.global.mount . }}/db"
  cert_dir: "{{ tpl .Values.global.mount . }}/ssl"


  ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIID1zCCAr+gAwIBAgIUZ439LYpChG3phSEAF8oPNuxwn2gwDQYJKoZIhvcNAQEL
    BQAwezEVMBMGA1UEAwwMKi5tZXRhdmFjLmFjMQ4wDAYDVQQLDAVJbmZyYTEQMA4G
    A1UECgwHTWV0YXZhYzETMBEGCgmSJomT8ixkARkWA2RldjEXMBUGCgmSJomT8ixk
    ARkWB21ldGF2YWMxEjAQBgoJkiaJk/IsZAEZFgJhYzAeFw0yMjAyMTAxOTEyMzRa
    Fw0yMzAyMTAxOTEyMzRaMHsxFTATBgNVBAMMDCoubWV0YXZhYy5hYzEOMAwGA1UE
    CwwFSW5mcmExEDAOBgNVBAoMB01ldGF2YWMxEzARBgoJkiaJk/IsZAEZFgNkZXYx
    FzAVBgoJkiaJk/IsZAEZFgdtZXRhdmFjMRIwEAYKCZImiZPyLGQBGRYCYWMwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCXb2e4Za/5er8gae0PZDZabfbu
    yNMMSEi+MTEfOlk7mkBY1XG8xyPWjnHknla6sRVtQFaN+BxmC1aju3dQP8KdIrRB
    Eb+/RwMMYr0F9pL1YuNXEZn2B0lNrC/f7xNsjsWuCtfNdeGOuhfefgkJaYZIxo9o
    Hp+vWG0bsjQrqFLpXVWfJBjeKrmfGjncAz/BORu5az/wU2N4svDiiUOaH0vTpde0
    QlfSBfQGmyKMg3zTr7x+YNURpTG2ucIBThik3tlKfO/bZ+bz4InIesVTjwEhuG8Z
    DGpyT31fQp3qomCS6+7I4zOa6umdO+XwKegpSvQu9RKfL5RjAQ8kilyweMgPAgMB
    AAGjUzBRMB0GA1UdDgQWBBRehTHZHDalW/bnO9PQ7h65AoF51TAfBgNVHSMEGDAW
    gBRehTHZHDalW/bnO9PQ7h65AoF51TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
    DQEBCwUAA4IBAQA75wk2uS1WzkcODCV6V/bREIggtggWYRdq4v51Fj3SRS9ck7AX
    o5AqjVG6iHs/yk/8x3gRlIlwZPivpgjT/EkkbevWUqVRIPzz4LdSIh/q9JBQz1E1
    lxGI5UdzKD+JhBvXybDDAV1UWIOB7Ahh3t2h6JhOM1D7npyICEjjzk+l3PUINZEs
    sVSpdu5J13dbljihaaRTfkCEi7fCsEFFLPgL/wtct88CfZAtEfT+DIAggZNZVgZf
    P94av3F0QsvTNmM/fMt/tiUQgaeXE4AGOZ0w5lIg4id8zzxedk8TcwPRsK56w0vp
    Ci5QrTnXSYKhqq6fGHDfUvTv6QhPZgPxQd/E
    -----END CERTIFICATE-----
  

mongodb-sharded:
  nameOverride: "metavac-db"
  clusterDomain: "db.dev.metavac.ac"
  shards: 2
  common:
    mongodbDirectoryPerDB: true
    extraEnvVars:
      - name: MONGODB_DATA_DIR
        value: "{{ .Values.global.mount }}"
    initContainers:
      - name: setup-certs
        image: "busybox:latest"
        command: ["sh", "-c", "set -x; sed \"s/id.pem/$(hostname).pem/g\" /bitnami/mongodb/conf/mongodb.conf > /bitnami/mongodb/conf/mongodb.conf"]
        volumeMounts: |
          {{- include "metavac-db.mongo.secrets.volume_mounts.configsvr" . -}}
  configsvr:
    replicas: 1
    config: "{{ include \"metavac-db.mongo.conf.configsvr\" . }}"
    podLabels:
      pod-name: configsvr
    persistence:
      mountPath: "/mnt/mongo"
      storageClass: "local-storage"
      size: "4Gi"
    extraVolumes: |
      {{ include "metavac-db.mongo.secrets.volumes.configsvr" . }}
      {{ include "metavac-db.mongo.bootstrap.volumes.configsvr" . }}
      {{ include "metavac-db.mongo.installshim.volumes" . }}
    extraVolumeMounts: |
      {{ include "metavac-db.mongo.secrets.volume_mounts.configsvr" . }}
      {{ include "metavac-db.mongo.bootstrap.volume_mounts.configsvr" . }}
      {{ include "metavac-db.mongo.installshim.volume_mounts" . }}
  mongos:
    replicas: 2
    config: "{{ include \"metavac-db.mongo.conf.mongos\" . }}"
    podLabels:
      pod-name: mongos
    useStatefulSet: true
    servicePerReplica:
      nodePort: 30007
    extraVolumes: |
      {{ include "metavac-db.mongo.secrets.volumes.mongos" . }}
      {{ include "metavac-db.mongo.bootstrap.volumes.mongos" . }}
    extraVolumeMounts: |
      {{ include "metavac-db.mongo.secrets.volume_mounts.mongos" . }}
      {{ include "metavac-db.mongo.bootstrap.volume_mounts.mongos" . }}
  shardsvr:
    replicas: 2
    config: "{{ include \"metavac-db.mongo.conf.shardsvr\" . }}"
    podLabels:
      pod-name: shardsvr
    persistence:
      mountPath: "/mnt/mongo"
      storageClass: "local-storage"
      size: "4Gi"
    extraVolumes: |
      {{ include "metavac-db.mongo.secrets.volumes.shardsvr" . }}
      {{ include "metavac-db.mongo.bootstrap.volumes.shardsvr" . }}
    extraVolumeMounts: |
      {{ include "metavac-db.mongo.secrets.volume_mounts.shardsvr" . }}
      {{ include "metavac-db.mongo.bootstrap.volume_mounts.shardsvr" . }}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}