# Default values for metavac-common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

cert_source_dir: "certs"

webhook:
  name: "default"
  domain: "dev.metavac.ac"
  service_account:
    name: "default-webhook-service-account"
    create: false
    nodeSelector: {}
    tolerations: []
    affinity: {}